import {
    Alert,
    Avatar,
    Badge,
    Box,
    Button,
    Card,
    Container,
    EmptyState,
    Flex,
    Heading,
    Image,
    Link,
    Paragraph,
    Section,
    SimpleCaption,
    SimpleTable,
    SimpleTbody,
    SimpleTd,
    SimpleTfoot,
    SimpleTh,
    SimpleThead,
    SimpleTr,
    Skeleton,
    Status,
    Table,
    Text,
    TextField,
} from "@odpf/apsara";
import { ArrowRightIcon, CaretDownIcon, CheckIcon, PlusIcon } from "@radix-ui/react-icons";
import type { ColumnDef } from "@tanstack/react-table";
import { createColumnHelper } from "@tanstack/react-table";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Hero } from "~/components/hero";

const inter = Inter({ subsets: ["latin"] });

export type Team = {
    id: string;
    name: string;
    slug: string;
    orgId: string;
    metadata: Record<string, string>;
    createdAt: string;
    updatedAt: string;
};

const columnHelper = createColumnHelper<Team>();
export const columns: ColumnDef<Team, any>[] = [
    {
        header: () => null,
        id: "select",
        cell: ({ row }) => <div></div>,
    },
    columnHelper.accessor("id", {
        header: "ID",
        cell: ({ row, getValue }) => {
            return <Link href={`${row.getValue("id")}`}>{getValue()}</Link>;
        },
    }),
    {
        header: "Organization ID",
        accessorKey: "orgId",
        cell: ({ row }) => <div>{row.getValue("id")}</div>,
    },

    {
        header: "Name",
        accessorKey: "name",
        cell: (info) => info.getValue(),
    },
    {
        header: "Slug",
        accessorKey: "slug",
        cell: (info) => info.getValue(),
        footer: (props) => props.column.id,
    },
    {
        header: "Create At",
        accessorKey: "createdAt",
        cell: (info) =>
            new Date(info.getValue() as Date).toLocaleString("en", {
                month: "long",
                day: "numeric",
                year: "numeric",
            }),

        footer: (props) => props.column.id,
    },
];

export default function Home() {
    return (
        <>
            <Head>
                <title>Apsara 2.0</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />

            <Section size="3">
                <Container size="2">
                    <Heading id="container" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                        Container
                    </Heading>
                </Container>
                <Container size="1">
                    <Box
                        css={{
                            p: "$5",
                            border: "1px solid $slate6",
                            borderRadius: "$3",
                        }}
                    >
                        <form>
                            <TextField
                                type="email"
                                size="2"
                                placeholder="Email"
                                autoComplete="off"
                                css={{ mb: "$3" }}
                            />
                            <TextField
                                type="password"
                                size="2"
                                placeholder="Password"
                                autoComplete="off"
                                css={{ mb: "$3" }}
                            />
                            <Flex direction="row" css={{ ai: "center", jc: "space-between" }}>
                                <Text size="2" css={{ color: "$slate11" }}>
                                    Forgot password
                                </Text>
                                <Button size="small" variant="primary">
                                    Log in
                                </Button>
                            </Flex>
                        </form>
                    </Box>
                </Container>
                <Container size="2" css={{ my: "$9" }}>
                    <Paragraph>
                        This is a really long paragraph of text, to demonstrate prose text, like for example, the kind
                        you might read in a blog post. The reason were using prose here is because the most common use
                        case for this container size is longform text. So were previewing some longform text here so we
                        can make sure the container width provides an optimal line length for this font size.
                    </Paragraph>
                </Container>
            </Section>
            <Section size="3">
                <Container size="2">
                    <Heading id="text" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                        Text
                    </Heading>
                    <Flex css={{ fd: "column", gap: "$4" }}>
                        <Flex css={{ ai: "center" }}>
                            <Text size="9" as="h1" css={{ fontWeight: 500, lineHeight: "55px" }}>
                                The quick brown fox
                            </Text>
                        </Flex>
                        <Flex css={{ ai: "center" }}>
                            <Text size="8" as="h2" css={{ fontWeight: 500, lineHeight: "37px" }}>
                                The quick brown fox jumped
                            </Text>
                        </Flex>
                        <Flex css={{ ai: "center" }}>
                            <Text size="7" as="h3" css={{ fontWeight: 500, lineHeight: "30px" }}>
                                The quick brown fox jumped
                            </Text>
                        </Flex>
                        <Flex css={{ ai: "center" }}>
                            <Text size="6" as="p" css={{ lineHeight: "30px" }}>
                                The quick brown fox jumped over the lazy dog.
                            </Text>
                        </Flex>
                        <Flex css={{ ai: "center" }}>
                            <Text size="5" as="p" css={{ lineHeight: "29px" }}>
                                The quick brown fox jumped over the lazy dog.
                            </Text>
                        </Flex>
                        <Flex css={{ ai: "center" }}>
                            <Text size="4" as="p" css={{ lineHeight: "29px" }}>
                                The quick brown fox jumped over the lazy dog.
                            </Text>
                        </Flex>
                        <Flex css={{ ai: "center" }}>
                            <Text size="3" as="p" css={{ lineHeight: "25px" }}>
                                The quick brown fox jumped over the lazy dog.
                            </Text>
                        </Flex>
                        <Flex css={{ ai: "center" }}>
                            <Text size="2" as="p" css={{ lineHeight: "20px" }}>
                                The quick brown fox jumped over the lazy dog.
                            </Text>
                        </Flex>
                        <Flex css={{ ai: "center" }}>
                            <Text size="1" as="p" css={{ lineHeight: "20px" }}>
                                The quick brown fox jumped over the lazy dog.
                            </Text>
                        </Flex>
                    </Flex>
                </Container>
            </Section>
            <Section size="3">
                <Container size="2">
                    <Heading id="skeleton" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                        Skeleton
                    </Heading>
                    <Heading css={{ mb: "$6" }}>Avatar variants</Heading>
                    <Flex
                        css={{
                            ai: "center",
                            gap: "$5",
                            fw: "wrap",
                            mb: "$7",
                        }}
                    >
                        <Skeleton variant="avatar1" />
                        <Skeleton variant="avatar2" />
                        <Skeleton variant="avatar3" />
                        <Skeleton variant="avatar4" />
                        <Skeleton variant="avatar5" />
                        <Skeleton variant="avatar6" />
                    </Flex>
                    <Heading css={{ mb: "$6" }}>Text variants</Heading>
                    <Flex
                        css={{
                            fd: "column",
                            gap: "$4",
                            mb: "$7",
                        }}
                    >
                        <Skeleton variant="title" css={{ width: "50%" }} />
                        <Skeleton variant="heading" css={{ width: "25%" }} />
                    </Flex>
                    <Flex
                        css={{
                            fd: "column",
                            gap: "$4",
                            mb: "$7",
                        }}
                    >
                        <Skeleton variant="text" />
                        <Skeleton variant="text" css={{ width: "75%" }} />
                        <Skeleton variant="text" />
                        <Skeleton variant="text" css={{ width: "50%" }} />
                    </Flex>
                    <Heading css={{ mb: "$6" }}>Control variants</Heading>
                    <Flex
                        css={{
                            fd: "column",
                            gap: "$4",
                        }}
                    >
                        <Skeleton variant="button" />
                    </Flex>
                </Container>
            </Section>
            <Section size="3">
                <Container size="2">
                    <Heading id="badge" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                        Badge
                    </Heading>
                    <Heading css={{ mb: "$6" }}>Default Badge</Heading>
                    <Badge css={{ mb: "$6" }}>Coming soon</Badge>
                    <Heading css={{ mb: "$6" }}>Sizes</Heading>
                    <Flex
                        css={{
                            ai: "center",
                            gap: "$5",
                            fw: "wrap",
                            mb: "$7",
                        }}
                    >
                        <Badge size="1">Coming soon</Badge>
                        <Badge size="2">Coming soon</Badge>
                    </Flex>
                    <Heading css={{ mb: "$6" }}>Variants</Heading>
                    <Flex css={{ gap: "$5", fw: "wrap", mb: "$6" }}>
                        <Badge size="2" variant="red">
                            <Box css={{ mr: 5 }}>
                                <Status size="1" variant="red" />
                            </Box>
                            Live
                        </Badge>
                        <Badge size="2" variant="crimson">
                            Approved
                        </Badge>
                        <Badge size="2" variant="pink">
                            Pending
                        </Badge>
                        <Badge size="2" variant="purple">
                            Failed
                        </Badge>
                        <Badge size="2" variant="violet">
                            New
                        </Badge>
                        <Badge size="2" variant="indigo">
                            Approved
                        </Badge>
                        <Badge size="2" variant="blue">
                            Pending
                        </Badge>
                        <Badge size="2" variant="cyan">
                            Failed
                        </Badge>
                        <Badge size="2" variant="teal">
                            New
                        </Badge>
                        <Badge size="2" variant="green">
                            Approved
                        </Badge>
                        <Badge size="2" variant="lime">
                            Pending
                        </Badge>
                        <Badge size="2" variant="yellow">
                            Failed
                        </Badge>
                        <Badge size="2" variant="orange">
                            Failed
                        </Badge>
                        <Badge size="2" variant="gold">
                            Winner
                        </Badge>
                        <Badge size="2" variant="bronze">
                            Runner-up
                        </Badge>
                    </Flex>
                    <Heading css={{ mb: "$6" }}>Interactive variant</Heading>
                    <Flex css={{ gap: "$5", fw: "wrap", mt: "$6" }}>
                        <Badge as="a" href="#" size="2" variant="red" interactive>
                            New
                        </Badge>
                        <Badge as="button" size="2" variant="crimson" interactive>
                            Approved
                        </Badge>
                        <Badge as="button" size="2" variant="pink" interactive>
                            Pending
                        </Badge>
                        <Badge as="button" size="2" variant="purple" interactive>
                            Failed
                            <Box css={{ ml: 5 }}>
                                <CaretDownIcon />
                            </Box>
                        </Badge>
                        <Badge as="button" size="2" variant="violet" interactive>
                            New
                        </Badge>
                        <Badge as="button" size="2" variant="indigo" interactive>
                            Approved
                        </Badge>
                        <Badge as="button" size="2" variant="blue" interactive>
                            Pending
                        </Badge>
                        <Badge as="button" size="2" variant="cyan" interactive>
                            Failed
                        </Badge>
                        <Badge as="button" size="2" variant="teal" interactive>
                            New
                        </Badge>
                        <Badge as="button" size="2" variant="green" interactive>
                            Approved
                        </Badge>
                        <Badge as="button" size="2" variant="lime" interactive>
                            Pending
                        </Badge>
                        <Badge as="button" size="2" variant="yellow" interactive>
                            Failed
                        </Badge>
                        <Badge as="button" size="2" variant="orange" interactive>
                            Failed
                        </Badge>
                        <Badge as="button" size="2" variant="gold" interactive>
                            Winner
                        </Badge>
                        <Badge as="button" size="2" variant="bronze" interactive>
                            Runner-up
                        </Badge>
                        <Badge as="button" size="2" variant="bronze" interactive disabled>
                            Disabled
                        </Badge>
                    </Flex>
                </Container>
            </Section>
            <Section size="3">
                <Container size="2">
                    <Heading id="alert" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                        Alert
                    </Heading>
                    <Flex css={{ gap: "$2", mt: "$6" }}>
                        <Alert variant="loContrast">
                            <Text size="3" css={{ fontWeight: 500, lineHeight: "20px", mb: "$1" }}>
                                Alert heading
                            </Text>
                            <Text size="2" variant="gray" css={{ lineHeight: "17px" }}>
                                A modal dialog that interrupts the user with <Link href="#">important content</Link> and
                                expects a response.
                            </Text>
                        </Alert>
                        <Alert variant="gray">
                            <Text size="3" css={{ fontWeight: 500, lineHeight: "20px", mb: "$1" }}>
                                Alert heading
                            </Text>
                            <Text size="2" variant="gray" css={{ lineHeight: "17px" }}>
                                A modal dialog that interrupts the user with <Link href="#">important content</Link> and
                                expects a response.
                            </Text>
                        </Alert>
                        <Alert variant="blue">
                            <Text size="3" variant="blue" css={{ fontWeight: 500, lineHeight: "20px", mb: "$1" }}>
                                Alert heading
                            </Text>
                            <Text size="2" variant="blue" css={{ lineHeight: "17px" }}>
                                A modal dialog that interrupts the user with <Link href="#">important content</Link> and
                                expects a response.
                            </Text>
                        </Alert>
                        <Alert variant="green">
                            <Text size="3" variant="green" css={{ fontWeight: 500, lineHeight: "20px", mb: "$1" }}>
                                Alert heading
                            </Text>
                            <Text size="2" variant="green" css={{ lineHeight: "17px" }}>
                                A modal dialog that interrupts the user with <Link href="#">important content</Link> and
                                expects a response.
                            </Text>
                        </Alert>
                        <Alert variant="red">
                            <Text size="3" variant="red" css={{ fontWeight: 500, lineHeight: "20px", mb: "$1" }}>
                                Alert heading
                            </Text>
                            <Text size="2" variant="red" css={{ lineHeight: "17px" }}>
                                A modal dialog that interrupts the user with <Link href="#">important content</Link> and
                                expects a response.
                            </Text>
                        </Alert>
                    </Flex>
                </Container>
            </Section>
            <Section size="3">
                <Container size="2">
                    <Heading id="button" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                        Button
                    </Heading>

                    <Flex css={{ mt: "$6", gap: "$6" }}>
                        <Button variant="primary" disabled>
                            Disabled
                        </Button>
                        <Button variant="primary">Active</Button>
                    </Flex>
                    <Flex css={{ gap: "$6", mt: "$6" }}>
                        <Button>
                            <Box
                                css={{
                                    mr: "$1",
                                }}
                            >
                                <PlusIcon />
                            </Box>
                            Button
                        </Button>
                        <Button variant="primary">
                            <Box
                                css={{
                                    mr: "$1",
                                }}
                            >
                                <PlusIcon />
                            </Box>
                            Button
                            <Box
                                css={{
                                    ml: "$1",
                                }}
                            >
                                <ArrowRightIcon />
                            </Box>
                        </Button>
                    </Flex>
                </Container>
            </Section>
            <Section size="3">
                <Container size="3">
                    <Container size="2">
                        <Heading id="card" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                            Card
                        </Heading>
                    </Container>
                    <Flex css={{ gap: "$3" }}>
                        <Box css={{ width: 250 }}>
                            <Card css={{ p: "$3" }}>
                                <Heading css={{ mb: "$2" }}>
                                    Modulz raises $4.2M to close the gap between design and code
                                </Heading>
                                <Text size="3" css={{ color: "$slate11", lineHeight: "23px" }}>
                                    Modulz is a visual code editor that empowers teams to design, develop, document and
                                    deploy a design system, without writing code.
                                </Text>
                            </Card>
                        </Box>
                        <Box css={{ width: 250 }}>
                            <Card as="a" href="#" css={{ p: "$3" }} variant="interactive">
                                <Heading css={{ mb: "$2" }}>
                                    Modulz raises $4.2M to close the gap between design and code
                                </Heading>
                                <Text size="3" css={{ color: "$slate11", lineHeight: "23px" }}>
                                    Modulz is a visual code editor that empowers teams to design, develop, document and
                                    deploy a design system, without writing code.
                                </Text>
                                <Flex css={{ ai: "center", jc: "space-between", mt: "$3" }}>
                                    <Flex css={{ ai: "center" }}>
                                        <Avatar
                                            size="2"
                                            alt="John Smith"
                                            src="https://pbs.twimg.com/profile_images/864164353771229187/Catw6Nmh_400x400.jpg"
                                            fallback="J"
                                            css={{
                                                mr: "$1",
                                            }}
                                        />
                                        <Text size="2" css={{ color: "$slate11" }}>
                                            Colm Tuite
                                        </Text>
                                    </Flex>
                                    <Box>
                                        <Text size="2" css={{ color: "$slate11" }}>
                                            May 2020
                                        </Text>
                                    </Box>
                                </Flex>
                            </Card>
                        </Box>
                        <Box css={{ width: 250 }}>
                            <Card as="a" href="#" variant="interactive">
                                <Image
                                    alt="image"
                                    src="https://images.unsplash.com/photo-1453235421161-e41b42ebba05?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=2550&q=80"
                                    css={{ btlr: "$3", btrr: "$3" }}
                                />
                                <Box css={{ p: "$3" }}>
                                    <Heading css={{ mb: "$2" }}>
                                        Modulz raises $4.2M to close the gap between design and code
                                    </Heading>
                                    <Text size="3" css={{ color: "$slate11", lineHeight: "23px" }}>
                                        Modulz is a visual code editor that empowers teams to design, develop, document
                                        and deploy a design system, without writing code.
                                    </Text>
                                    <Flex css={{ ai: "center", jc: "space-between", mt: "$3" }}>
                                        <Flex css={{ ai: "center" }}>
                                            <Avatar
                                                size="2"
                                                alt="John Smith"
                                                src="https://pbs.twimg.com/profile_images/864164353771229187/Catw6Nmh_400x400.jpg"
                                                fallback="J"
                                                css={{
                                                    mr: "$1",
                                                }}
                                            />
                                            <Text size="2" css={{ color: "$slate11" }}>
                                                Colm Tuite
                                            </Text>
                                        </Flex>
                                        <Box>
                                            <Text size="2" css={{ color: "$slate11" }}>
                                                May 2020
                                            </Text>
                                        </Box>
                                    </Flex>
                                </Box>
                            </Card>
                        </Box>
                        <Box css={{ width: 250 }}>
                            <Card as="a" href="#" variant="ghost" css={{ p: "$3" }}>
                                <Image
                                    alt="image"
                                    src="https://images.unsplash.com/photo-1453235421161-e41b42ebba05?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=2550&q=80"
                                    css={{ br: "$1", mb: "$3" }}
                                />
                                <Heading css={{ mb: "$2" }}>
                                    Modulz raises $4.2M to close the gap between design and code
                                </Heading>
                                <Text size="3" css={{ color: "$slate11", lineHeight: "23px" }}>
                                    Modulz is a visual code editor that empowers teams to design, develop, document and
                                    deploy a design system, without writing code.
                                </Text>
                                <Flex css={{ ai: "center", jc: "space-between", mt: "$3" }}>
                                    <Flex css={{ ai: "center" }}>
                                        <Avatar
                                            size="2"
                                            alt="John Smith"
                                            src="https://pbs.twimg.com/profile_images/864164353771229187/Catw6Nmh_400x400.jpg"
                                            fallback="J"
                                            css={{
                                                mr: "$1",
                                            }}
                                        />
                                        <Text size="2" css={{ color: "$slate11" }}>
                                            Colm Tuite
                                        </Text>
                                    </Flex>
                                    <Box>
                                        <Text size="2" css={{ color: "$slate11" }}>
                                            May 2020
                                        </Text>
                                    </Box>
                                </Flex>
                            </Card>
                        </Box>
                        <Box css={{ width: 250 }}>
                            <Card as="button" variant="active" css={{ p: "$3" }}>
                                <Text size="3" css={{ lineHeight: "23px", fontWeight: 500 }}>
                                    Default Variants
                                </Text>
                                <Text size="3" css={{ color: "$slate11", lineHeight: "23px" }}>
                                    Modulz is a visual code.
                                </Text>
                            </Card>
                        </Box>
                    </Flex>
                </Container>
            </Section>
            <Section size="3">
                <Container size="3">
                    <SimpleTable css={{ mt: "$7" }}>
                        <SimpleCaption>This is the table caption.</SimpleCaption>
                        <SimpleThead>
                            <SimpleTr>
                                <SimpleTh css={{ width: 190 }}>Club</SimpleTh>
                                <SimpleTd align="center">MP</SimpleTd>
                                <SimpleTd align="center">W</SimpleTd>
                                <SimpleTd align="center">D</SimpleTd>
                                <SimpleTd align="center">L</SimpleTd>
                                <SimpleTd align="center">GF</SimpleTd>
                                <SimpleTd align="center">GA</SimpleTd>
                                <SimpleTd align="center">GD</SimpleTd>
                                <SimpleTd align="center">Pts</SimpleTd>
                                <SimpleTd css={{ width: 100 }} align="center">
                                    Last 5
                                </SimpleTd>
                            </SimpleTr>
                        </SimpleThead>
                        <SimpleTbody>
                            <SimpleTr>
                                <SimpleTh css={{ width: 190 }}>
                                    <Flex>
                                        <Box css={{ width: "$5" }}>1</Box>
                                        Man City
                                    </Flex>
                                </SimpleTh>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">
                                    <Flex css={{ gap: "$1", jc: "flex-end" }}>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                    </Flex>
                                </SimpleTd>
                            </SimpleTr>
                        </SimpleTbody>
                        <SimpleTfoot>
                            <SimpleTr>
                                <SimpleTh css={{ width: 190 }}>
                                    <Flex>
                                        <Box css={{ width: "$5" }}>6</Box>
                                        Leicester City
                                    </Flex>
                                </SimpleTh>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">32</SimpleTd>
                                <SimpleTd align="center">
                                    <Flex css={{ gap: "$1", jc: "flex-end" }}>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                        <Box css={{ width: 15, height: 15, bc: "$green9", borderRadius: "$round" }}>
                                            <CheckIcon />
                                        </Box>
                                    </Flex>
                                </SimpleTd>
                            </SimpleTr>
                        </SimpleTfoot>
                    </SimpleTable>
                </Container>
            </Section>
            <Section size="3">
                <Container size="3">
                    <Container size="2">
                        <Heading id="card" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                            Empty table
                        </Heading>
                    </Container>
                    <Table columns={columns} data={[]} noDataChildren={noDataChildren}></Table>
                </Container>
                <Container size="3">
                    <Container size="2">
                        <Heading id="card" css={{ mb: "$6", scrollMarginTop: "$7" }}>
                            Table with data
                        </Heading>
                    </Container>
                    <Table
                        columns={columns}
                        data={[
                            {
                                id: "1",
                                name: "console",
                                slug: "console",
                                orgId: "1",
                                metadata: {},
                                createdAt: new Date().toString(),
                                updatedAt: new Date().toString(),
                            },
                        ]}
                        noDataChildren={noDataChildren}
                    ></Table>
                </Container>
            </Section>
        </>
    );
}

export const noDataChildren = (
    <EmptyState>
        <div className="svg-container"></div>
        <h3>0 teams created into your workspace</h3>
        <div className="pera">Try creating a new team.</div>
    </EmptyState>
);
