import { Link } from "@odpf/apsara";
import type { ColumnDef } from "@tanstack/react-table";
import { createColumnHelper } from "@tanstack/react-table";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Hero } from "~/components/hero";

const inter = Inter({ subsets: ["latin"] });

export type Team = {
    id: string;
    name: string;
    slug: string;
    orgId: string;
    metadata: Record<string, string>;
    createdAt: string;
    updatedAt: string;
};

const columnHelper = createColumnHelper<Team>();
export const columns: ColumnDef<Team, any>[] = [
    {
        header: () => null,
        id: "select",
        cell: ({ row }) => <div></div>,
    },
    columnHelper.accessor("id", {
        header: "ID",
        cell: ({ row, getValue }) => {
            return <Link href={`${row.getValue("id")}`}>{getValue()}</Link>;
        },
    }),
    {
        header: "Organization ID",
        accessorKey: "orgId",
        cell: ({ row }) => <div>{row.getValue("id")}</div>,
    },

    {
        header: "Name",
        accessorKey: "name",
        cell: (info) => info.getValue(),
    },
    {
        header: "Slug",
        accessorKey: "slug",
        cell: (info) => info.getValue(),
        footer: (props) => props.column.id,
    },
    {
        header: "Create At",
        accessorKey: "createdAt",
        cell: (info) =>
            new Date(info.getValue() as Date).toLocaleString("en", {
                month: "long",
                day: "numeric",
                year: "numeric",
            }),

        footer: (props) => props.column.id,
    },
];

export default function Home() {
    return (
        <>
            <Head>
                <title>Apsara 2.0</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
        </>
    );
}
