import { Inter } from "next/font/google";
import Head from "next/head";
import { Hero } from "~/components/hero";

const inter = Inter({ subsets: ["latin"] });

export type Team = {
  id: string;
  name: string;
  slug: string;
  orgId: string;
  metadata: Record<string, string>;
  createdAt: string;
  updatedAt: string;
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Apsara 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </>
  );
}
