// Shared Code Connect template for all Radix icons.
// Per-icon entries live in icons.figma.batch.json, which is generated by
// scripts/generate-icons-code-connect.js (run via `pnpm figma:generate-icons`)
// from the Figma icons file before publishing.
import figma from 'figma';

const name = figma.batch.component;

export default {
  id: name,
  imports: [`import { ${name} } from '@radix-ui/react-icons'`],
  example: figma.code`<${name} />`,
  metadata: { nestable: true }
};
