// This file is automatically generated by "npm run build:icons"
// Do not edit this file manually

export { ReactComponent as CheckCircleFilledIcon } from "./check-circle-filled.svg";
export { ReactComponent as CrossCircleFilledIcon } from "./cross-circle-filled.svg";
export { ReactComponent as FilterIcon } from "./filter.svg";
export { ReactComponent as OrganizationIcon } from "./organization.svg";
export { ReactComponent as SidebarIcon } from "./sidebar.svg";