// This file is automatically generated by "npm run build:icons"
// Do not edit this file manually

export { ReactComponent as CheckCircleFilledIcon } from "./assets/check-circle-filled.svg";
export { ReactComponent as CrossCircleFilledIcon } from "./assets/cross-circle-filled.svg";
export { ReactComponent as FilterIcon } from "./assets/filter.svg";
export { ReactComponent as OrganizationIcon } from "./assets/organization.svg";
export { ReactComponent as SidebarIcon } from "./assets/sidebar.svg";