import { Inter } from "next/font/google";
import Head from "next/head";
import { Box } from "~/components/box";
import { Button } from "~/components/button";
import { Flex } from "~/components/flex";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Apsara 2.0</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box as="main" className={inter.className} css={{ padding: "$4", maxWidth: "1200px", margin: "auto" }}>
                <Box>
                    <Flex direction="row" gap="6">
                        <Button size="small" variant="primary">
                            Button
                        </Button>
                        <Button variant="primary">Button</Button>
                        <Button size="large" variant="primary">
                            Button
                        </Button>
                    </Flex>

                    <Flex direction="row" gap="6" css={{ mt: "$6" }}>
                        <Button size="small">Button</Button>
                        <Button>Button</Button>
                        <Button size="large">Button</Button>
                    </Flex>
                </Box>
            </Box>
        </>
    );
}
