name: Release rc tag to NPM when a branch is merged to develop

on:
  push:
    branches:
      - develop

jobs:
  release-rc:
    name: Release RC
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm 9
        uses: pnpm/action-setup@v4
        with:
          version: 9.3.0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies 🔧
        run: pnpm install

      - name: Build Step 🔧
        env:
          CI: ""
        run: pnpm run ci:build

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump RC Package Version
        run: pnpm run bump-version-rc
        working-directory: ./packages/raystack

      - name: Run RC Release 🚀
        run: pnpm run release:rc
        working-directory: ./packages/raystack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate GitHub Release Notes 📓
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --repo "$GITHUB_REPOSITORY" \
            --generate-notes \
            --verify-tag
        

